version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - type: cache-restore
        name: Restore bundle cache
        keys:
          - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - type: cache-save
        name: Store bundle cache
        key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - type: cache-restore
        name: Restore yarn cache
        keys:
          - rails-demo-yarn-{{ checksum "yarn.lock" }}
          - rails-demo-yarn-

      - run:
          name: Yarn Install
          command: yarn install || yarn

      # Store yarn / webpacker cache
      - type: cache-save
        name: Store yarn cache
        key: rails-demo-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache
  deploy:
    machine:
      image: circleci/classic:edge
      environment:
        PATH: "registry.heroku.com/glacial-everglades-56011/node_modules/.bin"
    steps:
      - checkout
      # see: https://devcenter.heroku.com/articles/container-registry-and-runtime#using-a-ci-cd-platform
      - run:
          name: "build docker image"
          command: docker build --rm=false -t registry.heroku.com/glacial-everglades-56011/web .
      - run:
          name: setup heroku command
          command: bash .circleci/setup_heroku.sh
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app glacial-everglades-56011
      - run:
          # HEROKU_AUTH_TOKEN is generated by `heroku auth:token`
          name: "push container to registry.heroku.com"
          command: |
            docker login --username=_ --password=8638eb02-16b1-43aa-b409-a02274866f05 registry.heroku.com
            docker push registry.heroku.com/glacial-everglades-56011/web
      - run:
          name: heroku db migrate
          command: |
            heroku run yarn install --app glacial-everglades-56011
            heroku run yarn add material-design-lite --app glacial-everglades-56011
            heroku run rails db:migrate --app glacial-everglades-56011
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app glacial-everglades-56011
    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
